In [1]:
import pandas as pd
import numpy as np
from faker import Faker
from datetime import datetime, timedelta
import random

fake = Faker()

print("Setup Successful")

Setup Successful

In [2]:
# Doctors Dataset

specializations = [
    'Cardiologist',
    'Diabetologist',
    'General Physician',
    'Orthopedic',
    'Neurologist',
    'Gynecologist',
    'Dermatologist'
]

cities = [
    'Hyderabad',
    'Bangalore',
    'Chennai',
    'Mumbai',
    'Pune',
    'Delhi'
]

states = {
    'Hyderabad':'Telangana',
    'Bangalore':'Karnataka',
    'Chennai':'Tamil Nadu',
    'Mumbai':'Maharashtra',
    'Pune':'Maharashtra',
    'Delhi':'Delhi'
}

doctors = []

for i in range(1, 501):

    city = random.choice(cities)

    doctors.append([
        i,
        fake.name(),
        random.choice(specializations),
        fake.company() + " Hospital",
        city,
        states[city]
    ])

doctors_df = pd.DataFrame(
    doctors,
    columns=[
        'doctor_id',
        'doctor_name',
        'specialization',
        'hospital',
        'city',
        'state'
    ]
)

doctors_df.head()

,doctor_id,doctor_name,specialization,hospital,city,state
0,1,George Reyes,Cardiologist,Owens PLC Hospital,Bangalore,Karnataka
1,2,James Wilson,General Physician,Wilson Inc Hospital,Mumbai,Maharashtra
2,3,Robert Mcdonald,General Physician,Walker Ltd Hospital,Bangalore,Karnataka
3,4,Haley Wang,Diabetologist,Cantu PLC Hospital,Pune,Maharashtra
4,5,Christine Rhodes,Dermatologist,"Richardson, Tucker and Hughes Hospital",Delhi,Delhi

In [3]:
doctors_df.to_csv(
    '../01_Dataset/raw_data/doctors.csv',
    index=False
)

print("Doctors CSV Saved Successfully")

Doctors CSV Saved Successfully

In [4]:
# Products Dataset

categories = {
    'Cardiac': [
        'CardioPlus',
        'HeartSafe',
        'CardioCare',
        'PulseMax',
        'ArteryFlow',
        'CardioLife',
        'HeartWell',
        'CardioX',
        'VitaHeart',
        'CardioPrime'
    ],

    'Diabetes': [
        'DiaCare',
        'SugarFree',
        'GlucoMax',
        'DiaLife',
        'InsuCare',
        'GlucoSafe',
        'DiaPlus',
        'SugarShield',
        'DiaPrime',
        'GlucoCare'
    ],

    'Neuro': [
        'NeuroMax',
        'BrainPlus',
        'NeuroCare',
        'MindWell',
        'NeuroLife',
        'BrainSafe',
        'NeuroPrime',
        'NeuroX',
        'MindCare',
        'NeuroFlow'
    ],

    'Ortho': [
        'OrthoFlex',
        'BoneCare',
        'JointMax',
        'OrthoLife',
        'FlexiBone',
        'OrthoPrime',
        'JointCare',
        'BoneShield',
        'OrthoX',
        'FlexiCare'
    ],

    'Dermatology': [
        'SkinHeal',
        'DermaCare',
        'SkinPlus',
        'DermaSafe',
        'SkinGlow',
        'DermaLife',
        'SkinPrime',
        'DermaX',
        'GlowCare',
        'SkinShield'
    ]
}

products = []

product_id = 1

for category, names in categories.items():

    for product in names:

        products.append([
            product_id,
            product,
            category,
            round(random.uniform(50, 500), 2)
        ])

        product_id += 1

products_df = pd.DataFrame(
    products,
    columns=[
        'product_id',
        'product_name',
        'category',
        'price'
    ]
)

products_df.head()

   product_id product_name category   price
0           1   CardioPlus  Cardiac   89.95
1           2    HeartSafe  Cardiac  230.63
2           3   CardioCare  Cardiac  404.82
3           4     PulseMax  Cardiac   76.02
4           5   ArteryFlow  Cardiac  433.39

In [5]:
products_df.to_csv(
    '../01_Dataset/raw_data/products.csv',
    index=False
)

print("Products CSV Saved Successfully")

Products CSV Saved Successfully

In [6]:
products_df.shape

(50, 4)

In [7]:
doctors_df.shape
products_df.shape
medical_reps_df.shape

NameError: name 'medical_reps_df' is not defined

In [8]:
medical_reps_df.shape

NameError: name 'medical_reps_df' is not defined

In [9]:
doctors_df.shape

(500, 6)

In [10]:
products_df.shape

(50, 4)

In [11]:
regions = [
    'Hyderabad',
    'Bangalore',
    'Chennai',
    'Mumbai',
    'Pune',
    'Delhi'
]

medical_reps = []

for i in range(1, 101):

    joining_date = fake.date_between(
        start_date='-10y',
        end_date='today'
    )

    medical_reps.append([
        i,
        fake.name(),
        random.choice(regions),
        random.randint(1, 15),
        joining_date
    ])

medical_reps_df = pd.DataFrame(
    medical_reps,
    columns=[
        'mr_id',
        'mr_name',
        'region',
        'experience_years',
        'joining_date'
    ]
)

medical_reps_df.head()

   mr_id            mr_name   region  experience_years joining_date
0      1      Janet Solomon    Delhi                11   2026-03-02
1      2     Tina Contreras     Pune                 6   2025-11-30
2      3      Jasmine Ponce  Chennai                 7   2025-02-08
3      4       Tiffany Pham     Pune                12   2023-12-06
4      5  Michael Armstrong    Delhi                 8   2020-04-23

In [12]:
medical_reps_df.shape

(100, 5)

In [14]:
# Territory performance multipliers

territory_multiplier = {
    'Hyderabad': 1.30,
    'Bangalore': 1.20,
    'Mumbai': 1.15,
    'Delhi': 1.10,
    'Chennai': 1.00,
    'Pune': 0.90
}

In [15]:
# Product Price Lookup

product_price = dict(
    zip(
        products_df['product_id'],
        products_df['price']
    )
)

product_category = dict(
    zip(
        products_df['product_id'],
        products_df['category']
    )
)

doctor_specialization = dict(
    zip(
        doctors_df['doctor_id'],
        doctors_df['specialization']
    )
)

mr_experience = dict(
    zip(
        medical_reps_df['mr_id'],
        medical_reps_df['experience_years']
    )
)

In [16]:
len(product_price)

50

In [17]:
sales = []

for sale_id in range(1, 50001):

    mr_id = random.randint(1, 100)

    doctor_id = random.randint(1, 500)

    product_id = random.randint(1, 50)

    sale_date = fake.date_between(
        start_date='-2y',
        end_date='today'
    )

    territory = random.choice([
        'Hyderabad',
        'Bangalore',
        'Mumbai',
        'Delhi',
        'Chennai',
        'Pune'
    ])

    experience_factor = (
        mr_experience[mr_id] / 10
    )

    territory_factor = (
        territory_multiplier[territory]
    )

    units_sold = max(
        1,
        int(
            random.randint(5, 50)
            * experience_factor
            * territory_factor
        )
    )

    revenue = round(
        units_sold *
        product_price[product_id],
        2
    )

    sales.append([
        sale_id,
        sale_date,
        mr_id,
        doctor_id,
        product_id,
        units_sold,
        revenue,
        territory
    ])

sales_df = pd.DataFrame(
    sales,
    columns=[
        'sales_id',
        'sale_date',
        'mr_id',
        'doctor_id',
        'product_id',
        'units_sold',
        'revenue',
        'territory'
    ]
)

sales_df.head()

,sales_id,sale_date,mr_id,doctor_id,product_id,units_sold,revenue,territory
0,1,2024-11-21,88,430,23,35,12109.30,Bangalore
1,2,2025-08-14,85,347,15,15,1355.10,Delhi
2,3,2025-08-16,31,44,41,4,207.52,Chennai
3,4,2026-03-20,83,483,14,4,814.48,Pune
4,5,2025-01-09,76,499,28,56,9773.12,Pune

In [18]:
sales_df.shape

(50000, 8)

In [19]:
sales_df.to_csv(
    '../01_Dataset/raw_data/sales.csv',
    index=False
)

print("Sales CSV Saved Successfully")

Sales CSV Saved Successfully

In [20]:
prescriptions = []

for prescription_id in range(1, 20001):

    doctor_id = random.randint(1, 500)

    product_id = random.randint(1, 50)

    prescription_date = fake.date_between(
        start_date='-2y',
        end_date='today'
    )

    prescription_count = random.randint(1, 30)

    prescriptions.append([
        prescription_id,
        prescription_date,
        doctor_id,
        product_id,
        prescription_count
    ])

prescriptions_df = pd.DataFrame(
    prescriptions,
    columns=[
        'prescription_id',
        'prescription_date',
        'doctor_id',
        'product_id',
        'prescription_count'
    ]
)

prescriptions_df.head()

,prescription_id,prescription_date,doctor_id,product_id,prescription_count
0,1,2026-02-17,120,1,18
1,2,2025-05-12,60,48,24
2,3,2025-01-24,278,43,6
3,4,2024-11-05,79,18,28
4,5,2024-07-19,234,13,30

In [21]:
prescriptions_df.shape

(20000, 5)

In [22]:
prescriptions_df.to_csv(
    '../01_Dataset/raw_data/prescriptions.csv',
    index=False
)

print("Prescriptions CSV Saved Successfully")

Prescriptions CSV Saved Successfully

In [1]:
medical_reps_df.shape

NameError: name 'medical_reps_df' is not defined

In [2]:
import pandas as pd
from faker import Faker
import random

fake = Faker()

regions = [
    'Hyderabad',
    'Bangalore',
    'Chennai',
    'Mumbai',
    'Pune',
    'Delhi'
]

medical_reps = []

for i in range(1, 101):

    joining_date = fake.date_between(
        start_date='-10y',
        end_date='today'
    )

    medical_reps.append([
        i,
        fake.name(),
        random.choice(regions),
        random.randint(1, 15),
        joining_date
    ])

medical_reps_df = pd.DataFrame(
    medical_reps,
    columns=[
        'mr_id',
        'mr_name',
        'region',
        'experience_years',
        'joining_date'
    ]
)

medical_reps_df.to_csv(
    '../01_Dataset/raw_data/medical_reps.csv',
    index=False
)

print("medical_reps.csv saved")

medical_reps.csv saved

In [3]:
# Project Summary

print("Doctors:", doctors_df.shape)
print("Products:", products_df.shape)
print("Medical Reps:", medical_reps_df.shape)
print("Sales:", sales_df.shape)
print("Prescriptions:", prescriptions_df.shape)

NameError: name 'doctors_df' is not defined